// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database';

const SUPABASE_URL = "https://bsfgzhzuaeotgcpdcugq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZmd6aHp1YWVvdGdjcGRjdWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTMxNTAsImV4cCI6MjA2ODQ2OTE1MH0.-MJkFbFmDKkUmPzp24l64qUNwO9imQRNvo54rf3p5hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});